services:
  webserver:
    build: ./docker
    depends_on:
      - maria
    ports:
      - "80:80"
      - "443:443"
    hostname: npm.local
    working_dir: /var/www/main
    tty: true
    volumes:
      - .:/var/www/main
      - /tmp:/tmp
      - ./docker/config/conf.d:/etc/nginx/conf.d
      - ./docker/config/ssl:/etc/nginx/ssl
      - ./docker/logs:/var/log/nginx
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  maria:
    image: mariadb:11.5
    tty: true
    volumes:
      - maria-storage:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_HOST: "maria"
      MYSQL_DATABASE: "${DB_DATABASE:-mydb}"
      MYSQL_USER: "${DB_USERNAME:-myuser}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-secret}"
    ports:
      - "3306:3306"

volumes:
  maria-storage:
