version: '3.7'

services:

  revproxy:
    container_name: revproxy
    build: docker/nginx
    depends_on:
      - frontend
      - backend
    restart: always
    tty: true
    ports:
      - "${REVPROXY_PUBLIC_PORT:-80}:80"
    volumes:
      - ./docker/nginx/revproxy.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/revproxy:/var/log/nginx
      # Using timezone and system time from host
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      FRONTEND_DOMAIN: "${FRONTEND_DOMAIN:-frontend.local}"
      BACKEND_DOMAIN: "${BACKEND_DOMAIN:-backend.local}"

  frontend:
    container_name: frontend
    image: nginx:alpine
    tty: true
    ports:
      - ${FRONTEND_PUBLIC_PORT:-8081}:80
    restart: always
    working_dir: /var/www/main
    volumes:
      - ./frontend:/var/www/main
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/frontend:/var/log/nginx
      # Using timezone and system time from host
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  backend:
    container_name: backend
    image: nginx:alpine
    depends_on:
      - php-fpm
    links:
      - php-fpm
    ports:
      - "${BACKEND_PUBLIC_PORT:-8082}:80"
    restart: always
    tty: true
    working_dir: /var/www/main
    volumes:
      - ./backend:/var/www/main
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/backend:/var/log/nginx
      # Using timezone and system time from host
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  php-fpm:
    container_name: php
    build:
      context: ${contextdir}
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION:-8.1}"
        ENV: "${ENV:-production}"
    working_dir: /var/www/main
    volumes:
      - ./backend:/var/www/main
      # NOTE: If you've defined a PHP_VERSION like 7.4.28, you need to change here "8.1" to "7.4"!
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      # Using timezone and system time from host
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    links:
      - database
    depends_on:
      - database

  database:
    container_name: maria
    image: mariadb:${MARIADB_VERSION:-latest}
    tty: true
    volumes:
      - db-storage:/var/lib/mysql
      # Using timezone and system time from host
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_DATABASE: "${DB_NAME:-mydb}"
      MYSQL_USER: "${DB_USER:-root}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-root}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
    ports:
      - "${DB_PUBLIC_PORT:-3306}:3306"

volumes:
  db-storage: